Merge patches

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -9,12 +9,6 @@ unset GIT_DIR     # Avoid GIT_DIR leak from previous build steps
 
 [ "$BUILDPACK_XTRACE" ] && set -o xtrace
 
-### Constants
-
-# This is used by the buildpack stdlib for metrics
-# shellcheck disable=SC2034
-BPLOG_PREFIX="buildpack.basex"
-
 ### Configure directories
 
 BUILD_DIR=${1:-}
@@ -50,8 +44,6 @@ source "$BP_DIR/lib/plugin.sh"
 source "$BP_DIR/lib/uuid.sh"
 # shellcheck source=lib/kvstore.sh
 source "$BP_DIR/lib/kvstore.sh"
-# shellcheck source=lib/metadata.sh
-source "$BP_DIR/lib/metadata.sh"
 # shellcheck source=lib/features.sh
 source "$BP_DIR/lib/features.sh"
 # shellcheck source=lib/builddata.sh
@@ -67,7 +59,34 @@ export COREPACK_ENABLE_DOWNLOAD_PROMPT=0
 LOG_FILE=$(mktemp -t node-build-log.XXXXX)
 echo "" > "$LOG_FILE"
 
-build_start_time=$(nowms)
+
+build_start_time=$(build_data::current_unix_realtime)
+
+### Initialize metrics and features
+features_init "nodejs" "$BUILD_DIR" "$CACHE_DIR" "$BP_DIR/features"
+build_data::setup
+
+### Save build info
+
+# the "build-step" key keeps track of where we are in the execution so that we can see where failed builds errored
+build_data::set_string "build_step" "init"
+
+# capture procfile usage
+build_data::set_raw "has_procfile" "$(test -f "$BUILD_DIR/Procfile" && echo "true" || echo "false")"
+
+# capture scripts from package.json
+for script in heroku-prebuild heroku-postbuild build heroku-cleanup start postinstall; do
+  if [[ "$(has_script "$BUILD_DIR/package.json" "$script")" == "true" ]]; then
+    build_data::set_string "${script//[^[:alnum:]]/_}_script" "$(read_json "$BUILD_DIR/package.json" ".scripts[\"$script\"]")"
+  fi
+done
+
+# add any active features to the metadata set prefixed with the key "feature_"
+features_list | while read -r key; do
+  if [[ -n $key ]]; then
+    build_data::set_raw "feature_$key" "$(features_get "$key")"
+  fi
+done
 
 ### Handle errors
 
@@ -85,19 +104,9 @@ handle_failure() {
   warn_angular_resolution "$LOG_FILE"
   warn_missing_devdeps "$LOG_FILE" "$BUILD_DIR"
   warn_econnreset "$LOG_FILE"
-  log_meta_data >> "$BUILDPACK_LOG_FILE"
   failure_message | output "$LOG_FILE"
 }
 trap 'handle_failure' ERR
-
-### Initalize metadata store
-# Create the metadata store
-meta_init "$CACHE_DIR"
-# Make sure that it's empty and save any previous build's data
-meta_setup
-# the "build_step" key keeps track of where we are in the execution
-# so that we can see where failed builds errored
-meta_set "build_step" "init"
 
 ### Check initial state
 
@@ -106,10 +115,6 @@ meta_set "build_step" "init"
 [ -f "$BUILD_DIR/package-lock.json" ] && NPM_LOCK=true || NPM_LOCK=false
 [ -f "$BUILD_DIR/pnpm-lock.yaml" ] && PNPM=true || PNPM=false
 YARN_2=$(detect_yarn_2 "$YARN" "$BUILD_DIR")
-
-### Save build info
-features_init "nodejs" "$BUILD_DIR" "$CACHE_DIR" "$BP_DIR/features"
-log_initial_state
 
 ### Failures that should be caught immediately
 
@@ -209,11 +214,14 @@ install_bins() {
   basex_gzip=$(read_json "$BUILD_DIR/package.json" ".basex.gzip")
   basex_ignorecert=$(read_json "$BUILD_DIR/package.json" ".basex.ignorecert")
 
-  meta_set "node_version_request" "$node_engine"
-  meta_set "npm_version_request" "$npm_engine"
-  meta_set "yarn_version_request" "$yarn_engine"
-  meta_set "pnpm_version_request" "$pnpm_engine"
-  meta_set "package_manager_request" "$package_manager"
+  [ -n "$node_engine" ] && build_data::set_string "node_version_request" "$node_engine"
+  [ -n "$npm_engine" ] && build_data::set_string "npm_version_request" "$npm_engine"
+  [ -n "$yarn_engine" ] && build_data::set_string "yarn_version_request" "$yarn_engine"
+  [ -n "$pnpm_engine" ] && build_data::set_string "pnpm_version_request" "$pnpm_engine"
+  [ -n "$package_manager" ] && build_data::set_string "package_manager_request" "$package_manager"
+  [ -n "$jvm_engine" ] && build_data::set_string "jvm_engine_request" "$jvm_engine"
+  [ -n "$basex_engine" ] && build_data::set_string "basex_engine_request" "$basex_engine"
+  [ -n "$saxon_engine" ] && build_data::set_string "saxon_engine_request" "$saxon_engine"
 
   echo "engines.node (package.json):   ${node_engine:-unspecified}"
   echo "engines.npm (package.json):    ${npm_engine:-unspecified (use default)}"
@@ -230,9 +238,9 @@ install_bins() {
     echo "packageManager (package.json): $(echo "$package_manager" | cut -d "+" -f 1)"
   fi
 
-  meta_set "jvm-version-request" "$jvm_engine"
-  meta_set "basex-version-request" "$basex_engine"
-  meta_set "saxon-version-request" "$saxon_engine"
+  build_data::set_string "jvm-version-request" "$jvm_engine"
+  build_data::set_string "basex-version-request" "$basex_engine"
+  build_data::set_string "saxon-version-request" "$saxon_engine"
   echo "engines.jvm (package.json):   ${jvm_engine:-unspecified (use default)}"
   echo "engines.basex (package.json):   ${basex_engine:-unspecified (use default)}"
   if [ -n "$saxon_engine" ]; then
@@ -254,43 +262,44 @@ install_bins() {
     warn_yarn_release_script_with_package_manager "$package_manager" "$(get_yarn_path "$BUILD_DIR")"
   fi
 
-  meta_set "build_step" "install-nodejs"
+  build_data::set_string "build_step" "install-nodejs"
   monitor "install_node_binary" install_nodejs "$node_engine" "$BUILD_DIR/.heroku/node"
-
-  meta_set "build_step" "install-npm"
-  monitor "install_npm_binary" install_npm "$npm_engine" "$BUILD_DIR/.heroku/node" $NPM_LOCK
   
-  meta_set "build_step" "install-jvm"
+  build_data::set_string "build_step" "install-jvm"
   echo "java.runtime.version = $jvm_engine" >"${BUILD_DIR}/system.properties"
   monitor "install_jvm_binary" install_jdk "$jvm_engine" "$BUILD_DIR" $CACHE_DIR
   
-  meta_set "build_step" "install-basex"
+  build_data::set_string "build_step" "install-basex"
   monitor "install_basex_binary" install_basex "$basex_engine" "$BUILD_DIR/.heroku" $CACHE_DIR
   
   if [ -n "$saxon_engine" ]; then
-    meta_set "build_step" "install-saxon"
+    build_data::set_string "build_step" "install-saxon"
     monitor "install_saxon_binary" install_saxon "$saxon_engine" "$BUILD_DIR/.heroku/basex/lib/custom" $CACHE_DIR
   fi
 
+  build_data::set_string "node_version" "$(node --version)"
+  build_data::set_raw "node_version_major" "$(get_node_major_version)"
+  build_data::set_string "bundled_npm_version" "$(npm --version)"
   node_version="$(node --version)"
-  meta_set "node_version" "$node_version"
-  meta_set "node_version_major" "$(get_node_major_version)"
+
+  build_data::set_string "build_step" "install-npm"
+  install_npm "$npm_engine" "$BUILD_DIR/.heroku/node" "$NPM_LOCK"
 
   if ! has_release_script "$BUILD_DIR" && [[ "$package_manager" == yarn* ]]; then
-    meta_set "build_step" "install-yarn"
+    build_data::set_string "build_step" "install-yarn"
     monitor "install_yarn_binary" install_yarn_using_corepack_package_manager "$package_manager" "$node_version"
   else
     # Download yarn if there is a yarn.lock file or if the user
     # has specified a version of yarn under "engines". We'll still
     # only install using yarn if there is a yarn.lock file
     if $YARN || [ -n "$yarn_engine" ]; then
-      meta_set "build_step" "install-yarn"
+      build_data::set_string "build_step" "install-yarn"
       monitor "install_yarn_binary" install_yarn "$BUILD_DIR/.heroku/yarn" "$yarn_engine"
     fi
   fi
  
   if $PNPM; then
-    meta_set "build_step" "install-pnpm-using-corepack"
+    build_data::set_string "build_step" "install-pnpm-using-corepack"
 
     default_pnpm_version="pnpm@latest"
     using_default_pnpm=false
@@ -310,16 +319,21 @@ install_bins() {
     fi
   fi
 
-   if $YARN; then
-    meta_set "yarn_version" "$(yarn --version)"
-    meta_set "package_manager_version" "$(yarn --version)"
-   elif $PNPM; then
+  if $YARN; then
+    build_data::set_string "package_manager" "yarn"
+    build_data::set_string "package_manager_version" "$(yarn --version)"
+    build_data::set_string "yarn_version" "$(yarn --version)"
+  elif $PNPM; then
     meta_set "pnpm_version" "$(pnpm --version)"
     meta_set "package_manager_version" "$(pnpm --version)"
-   else
-    meta_set "npm_version" "$(npm --version)"
-    meta_set "package_manager_version" "$(npm --version)"
-   fi
+    build_data::set_string "package_manager" "pnpm"
+    build_data::set_string "package_manager_version" "$(pnpm --version)"
+    build_data::set_string "pnpm_version" "$(pnpm --version)"
+  else
+    build_data::set_string "package_manager" "npm"
+    build_data::set_string "package_manager_version" "$(npm --version)"
+    build_data::set_string "npm_version" "$(npm --version)"
+  fi
 
   warn_old_npm
 
@@ -335,7 +349,7 @@ install_bins() {
   patch -f "$BUILD_DIR/.profile.d/jvmcommon.sh" "$BP_DIR/lib/jvmcommon.sh.patch" 2>&1 > /dev/null
 
   jvm_version="$(java -version 2>&1 | grep version | sed -r 's/openjdk version "([^ ]+)"/\1/g')"
-  meta_set "jvm-version" "$jvm_version"
+  build_data::set_string "jvm-version" "$jvm_version"
   
   pushd "$BUILD_DIR/.heroku/basex/bin" >/dev/null
   mv "$BUILD_DIR/.heroku/basex/data" "$BUILD_DIR/.heroku/basex/data.image"
@@ -354,7 +368,7 @@ install_bins() {
   curl --connect-timeout 5 --max-time 10 --retry 3 --retry-delay 0  --retry-max-time 40 --retry-connrefused 1 -s -D - "http://localhost:$PORT" -o /dev/null 2>/dev/null | head -n1 | grep -q 200 || (pkill -TERM java; exit 1)
   basex_version=$($BUILD_DIR/.heroku/basex/bin/basexclient -Uadmin -P$BASEX_admin_pw -q \
   'db:system()/generalinformation/version/text()')
-  meta_set "basex-version" "$basex_version"
+  build_data::set_string "basex-version" "$basex_version"
   echo "Installed BaseX Version: $basex_version"
   popd >/dev/null
   
@@ -426,7 +440,7 @@ fi
 
 restore_cache() {
   local cache_status cache_directories restore_cache_start_time
-  restore_cache_start_time=$(nowms)
+  restore_cache_start_time=$(build_data::current_unix_realtime)
 
   cache_status="$(get_cache_status "$CACHE_DIR")"
   cache_directories="$(get_cache_directories "$BUILD_DIR")"
@@ -468,18 +482,21 @@ restore_cache() {
     :
   fi
 
-  meta_set "cache_status" "$cache_status"
-  meta_time "restore_cache_time" "$restore_cache_start_time"
+  # Remove any legacy cache contents written by older buildpack versions.
+  rm -rf "${CACHE_DIR}/build-data/nodejs" "${CACHE_DIR}/build-data/nodejs-prev"
+
+  build_data::set_string "cache_status" "${cache_status}"
+  build_data::set_duration "restore_cache_time" "${restore_cache_start_time}"
 }
 
-meta_set "build_step" "restore-cache"
+build_data::set_string "build_step" "restore-cache"
 restore_cache | output "$LOG_FILE"
 
 build_dependencies() {
   local cache_status start
 
   cache_status="$(get_cache_status "$CACHE_DIR")"
-  start=$(nowms)
+  start=$(build_data::current_unix_realtime)
   if [[ "$YARN_2" == "true" ]]; then
     yarn_2_install "$BUILD_DIR"
   elif $YARN; then
@@ -493,22 +510,22 @@ build_dependencies() {
     npm_node_modules "$BUILD_DIR"
   fi
 
-  meta_set "build_step" "build-script"
+  build_data::set_string "build_step" "build-script"
   header "Build"
   run_build_script "$BUILD_DIR"
 }
 
 log_build_scripts "$BUILD_DIR"
-meta_set "build_step" "prebuild-script"
+build_data::set_string "build_step" "prebuild-script"
 run_prebuild_script "$BUILD_DIR" | output "$LOG_FILE"
 
 header "Installing dependencies" | output "$LOG_FILE"
-meta_set "build_step" "install-dependencies"
+build_data::set_string "build_step" "install-dependencies"
 build_dependencies | output "$LOG_FILE"
 
 cache_build() {
   local cache_directories cache_build_start_time
-  cache_build_start_time=$(nowms)
+  cache_build_start_time=$(build_data::current_unix_realtime)
   cache_directories="$(get_cache_directories "$BUILD_DIR")"
 
   clear_cache "$CACHE_DIR"
@@ -524,7 +541,7 @@ cache_build() {
     save_custom_cache_directories "$BUILD_DIR" "$CACHE_DIR" "$cache_directories"
   fi
   save_signature "$CACHE_DIR"
-  meta_time "save_cache_time" "$cache_build_start_time"
+  build_data::set_duration "save_cache_time" "$cache_build_start_time"
 }
 
 prune_devdependencies() {
@@ -538,46 +555,43 @@ prune_devdependencies() {
 }
 
 if $YARN_2; then
-  meta_set "build_step" "save-cache"
+  build_data::set_string "build_step" "save-cache"
   cache_build | output "$LOG_FILE"
-  meta_set "build_step" "prune-dependencies"
+  build_data::set_string "build_step" "prune-dependencies"
   header "Pruning devDependencies" | output "$LOG_FILE"
   prune_devdependencies | output "$LOG_FILE"
 elif "$YARN" && "$USE_YARN_CACHE" && [[ "$(get_cache_directories "$BUILD_DIR")" == "" ]]; then
-  meta_set "build_step" "prune-dependencies"
+  build_data::set_string "build_step" "prune-dependencies"
   header "Pruning devDependencies" | output "$LOG_FILE"
   prune_devdependencies | output "$LOG_FILE"
-  meta_set "build_step" "save-cache"
+  build_data::set_string "build_step" "save-cache"
   cache_build | output "$LOG_FILE"
 else
-  meta_set "build_step" "save-cache"
+  build_data::set_string "build_step" "save-cache"
   cache_build | output "$LOG_FILE"
-  meta_set "build_step" "prune-dependencies"
+  build_data::set_string "build_step" "prune-dependencies"
   header "Pruning devDependencies" | output "$LOG_FILE"
   prune_devdependencies | output "$LOG_FILE"
 fi
 
-meta_set "build_step" "cleanup-script"
+build_data::set_string "build_step" "cleanup-script"
 run_cleanup_script "$BUILD_DIR" | output "$LOG_FILE"
 
 summarize_build() {
   if $NODE_VERBOSE; then
     list_dependencies "$BUILD_DIR"
   fi
-
-  meta_set "node-modules-size" "$(measure_size)"
 }
 
-meta_set "build_step" "install-metrics-plugin"
+build_data::set_string "build_step" "install-metrics-plugin"
 install_plugin "$BP_DIR" "$BUILD_DIR"
 
-meta_set "build_step" "summarize"
+build_data::set_string "build_step" "summarize"
 header "Build succeeded!" | output "$LOG_FILE"
 summarize_build | output "$LOG_FILE"
-meta_time "build_time" "$build_start_time"
+build_data::set_duration "build_time" "$build_start_time"
 
 warn_unmet_dep "$LOG_FILE"
 warn_old_npm_lockfile "$NPM_LOCK"
 
-meta_set "build_step" "finished"
-log_meta_data >> "$BUILDPACK_LOG_FILE"
+build_data::set_string "build_step" "finished"
